services/app/config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  root 'welcome#index', as: 'home'

  resources :articles do
    resources :comments, only: [:index, :show]
  end

  resources :categories, only: [:show]

  get 'about' => 'pages#about'

  namespace :admin do
    resources :categories, except: [:show]
    resources :articles, except: [:index, :show]
  end
end

services/app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

services/app/app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :category

  validates :title, :text, presence: true
  validates :title, length: { minimum: 5, maximum: 250 }
end

services/app/app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

services/app/app/models/category.rb
class Category < ApplicationRecord
  has_many :articles
  validates :name, presence: true
end

services/app/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

services/app/app/models/guest.rb
class Guest
  def guest?
    true
  end

  def role?(role)
    false
  end
end

services/app/app/models/role.rb
class Role < ApplicationRecord
  has_many :users

  validates :name, presence: true, uniqueness: true
end

services/app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  belongs_to :role
  before_validation :set_default_role

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def role?(role)
    roles.any? { |r| r.name.to_sym == role }
  end

  def guest?
    false
  end

  private
  def set_default_role
    self.role ||= Role.find_by_name('user')
  end
end

services/app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Flash
  protect_from_forgery with: :exception
  helper_method :menu_categories

  def menu_categories
    @menu_categories ||= Category.all
  end

  def current_user
    super || Guest.new
  end
end

services/app/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

services/app/app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user
      set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
    else
      session['devise.github_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  # def failure
  #   redirect_to home_path
  # end
end

services/app/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @articles = Article.where(category_id: params[:id])
  end
end

services/app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commentor, :body)
  end
end

services/app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

services/app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

services/app/app/helpers/application_helper.rb
module ApplicationHelper
end

services/app/app/helpers/articles_helper.rb
module ArticlesHelper
end

services/app/app/helpers/comments_helper.rb
module CommentsHelper
end

services/app/app/helpers/pages_helper.rb
module PagesHelper
end

services/app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

services/app/app/views/layouts/_nav.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  = link_to t('title'), home_path, class: 'navbar-brand'

  button.navbar-toggler data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
    span.navbar-toggler-icon

  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav
      li.nav-item
        = link_to 'Blog', articles_path, class:(['nav-link', current_page?(articles_path) && 'active'])
    ul.navbar-nav.ml-auto
      - if current_user.guest?
        = link_to 'Sign In', new_user_session_path, class: 'nav-link'
      - else
        = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'

services/app/app/views/layouts/application.html.slim
doctype html
html.h-100 lang="#{I18n.locale}"
  meta charset="utf-8"
  meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
  meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
  title = t('title')
  = favicon_link_tag
  = csrf_meta_tags
  = stylesheet_link_tag "application", media: "all"
  = javascript_include_tag "application"

body.container
  = render 'layouts/nav'
  = render_flash_messages dismissible: true
  .row
    .col-md-3
      = render 'shared/menu'
    .col-md-9
      = yield

services/app/app/views/pages/about.html.slim
h4= 'About'

services/app/app/views/shared/_menu.html.slim
h3= 'Categories'

- menu_categories.each do |category|
  = link_to category.name, category_path(category)